# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.cache/wt [current_project]
set_property parent.project_path D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/captura.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/pkg_fun.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/pkg_ov7670.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/color_proc.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/pkg_sum.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/comparador.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/pkg_gral.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/pkg_vga.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/pkg_osc.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/control.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/debounce.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/disp7seg_8dig.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/edge_proc.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/flanco_restart.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/frame_buffer.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/oscop_bram.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/oscop_control.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/oscop_display.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/oscop_top.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/ov7670_capture.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/ov7670_ctrl_reg.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/ov7670_top_ctrl.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/pkg_util.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/proc_serie.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/ram_sum.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/sccb_master.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/stepper_motor.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/sumador.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/top_posicionamiento.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/top_sum.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/uart_rx.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/top_uart_rx.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/uart_interfaz.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/new/uart_tx_nopar.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/vga_display.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/vga_sync.vhd
  D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/sources_1/imports/vhd/top_ov7670.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/constrs_1/imports/Desktop/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files D:/carlo/UNIVERSIDAD/TFM/MICROSCOPIO/full_micro_V2/full_micro_V2.srcs/constrs_1/imports/Desktop/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_ov7670 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_ov7670.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_ov7670_utilization_synth.rpt -pb top_ov7670_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
